[package]
name = "blog_os-riscv"
version = "0.1.0"
authors = [
	"Ryota Ozaki <ozaki.ryota@gmail.com>",
	"Philipp Oppermann <dev@phil-opp.com>"
]
edition = "2018"

[dependencies]
#bootloader = "0.8.0"
#cc = "1.0.25"
